# github action config auto update database

name: Update database

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.12

      - name: Install modules
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main bruh
        run: python main.py --help
      
      - name: Checking Any updated or not
        id: git-status
        run: |
          changes=$(git status --porcelain)
          echo "changes=${changes}" >> $GITHUB_ENV

      - name: Start Push
        run: |
          git config --local user.name ${{ secrets.GH_USERNAME }}
          git config --local user.email ${{ secrets.GH_EMAIL }}
          git status
          git add .
          git commit -m "Last Up: $(py -c 'from datetime import datetime; print(datetime.now().strftime("%B %d - %I:%M:%S %p"))') - with length: $(cat database/Nekopoi-hentai-list.json | jq | jq length)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
        if: env.CHANGES != ''
